# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Languages
languages: ["en", "ja"]
default_lang: "en"

# 多语言内容
translations:
  en:
    sections:
      about: "About Me"
      experience: "Experience"
      tech_stack: "Tech Stack"
      education: "Education"
      languages: "Languages"
      personal_pj: "Personal Projects"
    title: "Analytics Engineer"
  ja:
    sections:
      about: "自己紹介"
      experience: "職歴"
      tech_stack: "スキルセット"
      education: "学歴"
      languages: "言語能力"
      personal_pj: "個人プロジェクト"
    title: "アナリティクスエンジニア"

# Personal info
name: QU GUANGYU
name_ja: 曲 光鈺
title: Analytics Engineer
email: quguangyu0321@gmail.com
website: https://medium.com/@quguangyu0321

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: quguangyu
linkedin_username: guangyu-qu-a51b661a6
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: redbook
  icon: fas fa-globe
  # icon: https://fontawesome.com/icons/book?f=classic&s=solid
  url: https://www.xiaohongshu.com/user/profile/5b1c88d96b58b70d9fb75e3e?xsec_token=YBhNsDHtxfT0xAyVm9ApdDk5dV7rMGmPMrLlLsLrB3wpI%3D&xsec_source=app_share&xhsshare=CopyLink&appuid=5b1c88d96b58b70d9fb75e3e&apptime=1741935998&share_id=0f9df8401db04df0ae65121a9324677d&share_channel=copy_link
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
    With 8 years of experience as a <mark>Full Stack Data Scientist</mark> at NTT GROUP, I have led to significant, continuous improvements in data systems.
    Proficient in <mark>Databases</mark>, <mark>CI/CD</mark>, <mark>Data Pipelines</mark>, <mark>Business Intelligence (BI)</mark>, <mark>SQL</mark>, and <mark>Python</mark>, demonstrating a wide range of skills for different types of data problems.

    My expertise spans  <mark>Fraud Analysis</mark>, <mark>Marketing</mark>, <mark>HR-tech</mark>, and <mark>global IoT connectivity</mark> among other areas.

    Currently managing the delivery of large-scale telematics projects for leading automotive brands worldwide. I ensure seamless coordination between customer requirements and technical execution, optimizing service deployment and driving project success across multiple regions.

    Beyond IoT and connectivity, I am actively exploring AI applications, leveraging <mark>LLMs</mark>, Model Context Protocol (<mark>MCP</mark>), and other advanced technologies to develop intelligent business tools. Committed to continuous learning, I stay at the forefront of technological advancements to drive innovation and efficiency.

about_content_ja: | # 日本語版自己紹介
    NTTグループにて8年間の<mark>アナリティクスエンジニア</mark>としての経験を持ち、データシステムの大幅な継続的改善に貢献してきました。
    <mark>データベース</mark>、<mark>CI/CD</mark>、<mark>データパイプライン</mark>、<mark>ビジネスインテリジェンス（BI）</mark>、<mark>SQL</mark>、<mark>Python</mark>に精通しており、様々なタイプのデータ問題に対応するための幅広いスキルを実証しています。

    専門分野として<mark>不正分析</mark>、<mark>マーケティング</mark>、<mark>HRテック</mark>、<mark>グローバルIoT接続</mark>などがあります。

    現在は、世界中の主要自動車ブランド向けの大規模なテレマティクスプロジェクトの提供を管理しています。顧客要件と技術的実装の間のシームレスな調整を確保し、サービスデプロイメントを最適化し、複数の地域にわたるプロジェクト成功を推進しています。

    IoTと接続性を超えて、<mark>LLM</mark>、モデルコンテキストプロトコル（<mark>MCP</mark>）などの高度な技術を活用したAIアプリケーションも積極的に探求し、インテリジェントなビジネスツールの開発に取り組んでいます。継続的学習に取り組み、技術的進歩の最前線に立ち、革新と効率性を推進しています。

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    title_ja: 職歴 # 日本語タイトル
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: NTT Docomo Business
        link: https://www.ubigi.com/connected-cars/
        # link_text: boringcompany.com
        sub_title: Presales Engineer(5G&IOT), Tokyo
        sub_title_ja: プリセールスエンジニア、東京
        caption: December 2024 - Present
        caption_ja: 2024年12月 - 現在
        description: | # this will include new lines to allow paragraphs
            - Led proposals and delivery support for both domestic and international connected car projects by understanding unique IT system requirements and collaborating with internal teams and global partners.
            - Acted as a solution architect, ensuring successful IT system delivery for connected car projects.
            - Offer technical guidance and support to the sales team on topics such as <mark>mobile networks</mark>, <mark>SASE</mark>, and <mark>IoT devices</mark>.
            - Independently designed and managed system architectures integrating mobile and IT technologies with multi-vendor platforms.
        description_ja: | # 日本語説明
            - 国内外のコネクテッドカープロジェクトのための提案と納品サポートをリードし、独自のITシステム要件を理解し、社内チームやグローバルパートナーと協働しています。
            - ソリューションアーキテクトとして、コネクテッドカープロジェクトのITシステム納品の成功を確保しています。
            - 営業チームに対し、（<mark>モバイルNW</mark>、<mark>SASE</mark>、<mark>IoT機器</mark>などの）技術支援を行います。
            - モバイル技術とITテクノロジーをマルチベンダープラットフォームと統合するシステムアーキテクチャを独立して設計・管理しています。

      - layout: left
        border: weak
        title: Transatel
        link: https://cellulardata.ubigi.com
        # link_text: boringcompany.com
        sub_title: Analystics Engineer, Paris
        sub_title_ja: アナリティクスエンジニア、パリ
        caption: December 2023 - November 2024
        caption_ja: 2023年12月 - 2024年11月
        description: | # this will include new lines to allow paragraphs
              I play a dual role, contributing to both the Marketing and Business Intelligence (BI) teams.
              - Led in-depth marketing analysis for <mark>Ubigi</mark>'s eSIM service(travel data from around the world), leveraging advanced data analytics to drive strategic decisions and enhance service offerings.
              - Collaborated closely with the <mark>Business Intelligence</mark> (BI) team to facilitate a seamless BI Platform Migration of the BI platform from on-premises to Snowflake, significantly improving data processing efficiency and scalability.
        description_ja: | # 日本語説明
              マーケティングチームとビジネスインテリジェンス（BI）チームの両方に貢献する二重の役割を果たしています。
              - <mark>Ubigi</mark>のeSIMサービス（世界中の旅行データ）のための詳細なマーケティング分析をリードし、高度なデータ分析を活用して戦略的決定とサービス提供の向上を推進しています。
              - ビジネスインテリジェンス（<mark>BI</mark>）チームと緊密に協力し、BIプラットフォームをオンプレミスからSnowflakeへ移行するプロセスを促進し、データ処理効率とスケーラビリティを大幅に向上させました。

      - layout: left
        border: weak
        title: Docomo Pacific
        link: https://www.docomopacific.com
        # link_text: boringcompany.com
        sub_title: Analystics Engineer, Guam
        sub_title_ja: アナリティクスエンジニア、グアム
        caption: April 2023 - September 2023
        caption_ja: 2023年4月 - 2023年9月
        description: | # this will include new lines to allow paragraphs
              I spearheaded a six-month project where I served as the lead trainer for Guam's BI team.
              I designed and delivered interactive, hands-on workshops to empower them in mastering <mark>Power BI</mark>, while also providing expert guidance on executing comprehensive customer satisfaction survey analyses.
        description_ja: | # 日本語説明
              私は6ヶ月間のプロジェクトをリードし、グアムのBIチームの主任トレーナーを務めました。
              <mark>Power BI</mark>の習得を支援するためのインタラクティブなハンズオンワークショップを設計・提供し、包括的な顧客満足度調査分析の実施に関する専門的なガイダンスも提供しました。

      - layout: left
        border: weak
        title: NTT Communications
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Analystics Engineer(DX), Tokyo
        sub_title_ja: アナリティクスエンジニア、東京
        caption: April 2020 - November 2023
        caption_ja: 2020年4月 - 2023年11月
        description: | # this will include new lines to allow paragraphs
                 <mark>Center of Excellence(COE)</mark> in Data Analysis. Work as an analysis consultant to help staff improve their analytical skills. Identifying problems in business processes and redesigning them in a modern digital way.
                 I also serve as a link between the <mark>data engineer</mark> and <mark>data analyst</mark> teams within the big data group. Create services and teach the analysis team how to use the system.
                 - I have experience in driving business transformation for the internal audit team by helping them efficiently analyze internal risk and perform effective audits.(<mark>Fraud Analysis</mark>)
                 - I supported the HR department by analyzing investigations of employee engagement. Through this role, I helped HR identify areas of concern and implemented solutions to improve employee satisfaction and retention.(<mark>HR Analysis</mark>)
                 - I led to discuss and build data modeling guildline in bigdata team. Standardlize the process from source layer to dwh layer and datamart layer(<mark>Data Modeling</mark>).
                 - I have experience in proof of concept and implementation of <mark>Data Virtualization</mark> solutions ( Denodo) and <mark>Data Catalog</mark> solutions to help users accelerate their analysis.
        description_ja: | # 日本語説明
                 <mark>COE組織</mark>であり、分析コンサルタントとして、スタッフが分析スキルを向上させるのを支援しています。ビジネスプロセスの問題を特定し、現代的なデジタル方法で再設計しています。
                 また、ビッグデータグループ内の<mark>データエンジニアチーム</mark>と<mark>データアナリストチーム</mark>の間の橋渡し役も務めています。サービスを作成し、分析チームにシステムの使用方法を教えています。
                 - <mark>内部監査</mark>チームのビジネス変革を推進し、内部リスクの効率的な分析と効果的な監査の実施を支援した経験があります。（<mark>不正分析</mark>）
                 - 従業員エンゲージメントの調査分析を通じてHR部門をサポートしました。この役割を通じて、HR部門が懸念領域を特定し、従業員満足度と定着率を向上させるソリューションを実装するのを支援しました。（<mark>HR分析</mark>）
                 - ビッグデータチームのデータモデリングガイドラインの議論と構築をリードしました。ソースレイヤーからDWHレイヤーとデータマートレイヤーへのプロセスを標準化しました。（<mark>データモデリング</mark>）
                 - <mark>データ仮想化ソリューション</mark>（Denodo）と<mark>データカタログ</mark>ソリューションの概念実証と実装の経験があり、ユーザーが分析を加速するのを支援しています。

      - layout: left
        border: weak
        title: NTT Communications
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DBA+PM(Customer Service), Tokyo
        sub_title_ja: DBA+PM、東京
        caption: April 2017 - March 2020
        caption_ja: 2017年4月 - 2020年3月
        description: | # this will include new lines to allow paragraphs
                Project Manager responsible for the maintenance of the on-premise <mark>Oracle</mark> EXADATA Database Machine platform. Reviewing daily tasks such as capacity planning, performance monitoring, security, backups, troubleshooting, and data recovery. 
                - Designing and implementing a disaster backup site in a different region to ensure business continuity.
                - Designing and implementing an <mark>ETL</mark> platform using OSS Talend Data Studio for the DWH team, resulting in faster data integration processes.
        description_ja: | # 日本語説明
                オンプレミスの<mark>Oracle</mark> EXADATAデータベースマシンプラットフォームの保守を担当するプロジェクトマネージャー。容量計画、パフォーマンス監視、セキュリティ、バックアップ、トラブルシューティング、データ復旧などの日常的なタスクをレビューしています。
                - ビジネス継続性を確保するため、異なる地域に災害バックアップサイトを設計・実装しました。
                - DWHチーム向けにOSS Talend Data Studioを使用した<mark>ETL</mark>プラットフォームを設計・実装し、より迅速なデータ統合プロセスを実現しました。

      - layout: left
        title: NTT Communications
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Developer(Customer Service), Tokyo
        sub_title_ja: ソフトウェア開発者、東京
        caption: April 2016 - March 2017
        caption_ja: 2016年4月 - 2017年3月
        description: | # this will include new lines to allow paragraphs
                  I have experience in developing a Master IT Facility Management System that collects and manages data from servers, network devices, and Excel files, providing reliable information via a web GUI for operators. 
                  - Constructing Linux/Windows servers and virtualized environments using <mark>Openstack</mark>, <mark>Docker</mark>, and <mark>Ansible</mark> in an on-premise setting.
                  - Designing and implementing a Storage Area Network (SAN) composed of <mark>Servers</mark>, <mark>FC-switches</mark>, and <mark>VNX Storage</mark>.
                  - Installing and configuring a <mark>Zabbix</mark> monitoring system to monitor Servers, storage, FC-switches, and developed applications running on servers.
                  - Writing automated web application tests using <mark>Selenium</mark> and <mark>Python</mark>.
        description_ja: | # 日本語説明
                  サーバー、ネットワークデバイス、Excelファイルからデータを収集・管理し、オペレーターにWebGUIを通じて信頼性の高い情報を提供するマスターITファシリティ管理システムの開発経験があります。
                  - オンプレミス環境で<mark>Openstack</mark>、<mark>Docker</mark>、<mark>Ansible</mark>を使用したLinux/Windowsサーバーと仮想化環境の構築を行いました。
                  - <mark>サーバー</mark>、<mark>FCスイッチ</mark>、<mark>VNXストレージ</mark>で構成されるストレージエリアネットワーク（SAN）の設計と実装を行いました。
                  - サーバー、ストレージ、FCスイッチ、サーバー上で実行される開発されたアプリケーションを監視する<mark>Zabbix</mark>監視システムのインストールと設定を行いました。
                  - <mark>Selenium</mark>と<mark>Python</mark>を使用した自動化されたWebアプリケーションテストの作成を行いました。

  - title: Tech Stack # Title for the section
    title_ja: テックスタック # 日本語タイトル
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - **5G&IOT** (CellularNW, SASE, etc)
      - **AI** (Lamaindex, LLM, Vector Database, etc)
      - **Database** (Duckdb, Snowflake, Hadoop, Hive, Trino, Clickhouse, Kafka, Oracle, Mysql,etc)
      - **BI Tools** (Tableau, PowerBI, Superset, Streamlit)
      - **Metadata Management** (Datahub, OpenMetadata)
      - **Data Virturalization** (denodo, tibco)
      - **ETL/ELT** (DBT, Airflow, Talend, Airbyte)
      - **Data Quality** (Dbt test, Great expectations, Pytest)
      - **Infra** (K8S, Helm, ArgoCD,Ansible, Selenium, Sphinx,etc)
      - **Log Management** (Elasticsearch, Kibana, Logstash, Beatsfamily)
      - **Microsoft Solution** (GraphAPI, AzureAD, AzureSQL, WindowsServer etc)
    content_ja: | # 日本語コンテンツ
      - **5G&IOT** (モバイルNW, SASE, etc)
      - **AI** (Lamaindex, LLM, Vector Database, etc)
      - **データベース** (Duckdb, Snowflake, Hadoop, Hive, Trino, Clickhouse, Kafka, Oracle, Mysql等)
      - **BIツール** (Tableau, PowerBI, Superset, Streamlit)
      - **メタデータ管理** (Datahub, OpenMetadata)
      - **データ仮想化** (denodo, tibco)
      - **ETL/ELT** (DBT, Airflow, Talend, Airbyte)
      - **データ品質** (Dbt test, Great expectations, Pytest)
      - **インフラ** (K8S, Helm, ArgoCD,Ansible, Selenium, Sphinx等)
      - **ログ管理** (Elasticsearch, Kibana, Logstash, Beatsfamily)
      - **Microsoft Solutions** (GraphAPI, AzureAD, AzureSQL, WindowsServer等)

  - title: Education # Title for the section
    title_ja: 学歴 # 日本語タイトル
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - 2014-2016, Master(Cognitive and Behavioral Sciences), Kyoto University, Kyoto
      - 2009-2013, Bachelor(Information Sciences), Tianjin University, Tianjin
    content_ja: | # 日本語コンテンツ
      - 2014-2016、修士（認知・行動科学）、京都大学、京都
      - 2009-2013、学士（情報科学）、天津大学、天津

  - title: Languages # Title for the section
    title_ja: 言語能力 # 日本語タイトル
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - Mandarin(Native)
      - Japanese(High Proficiency)
      - English(Business)
    content_ja: | # 日本語コンテンツ
      - 中国語（ネイティブ）
      - 日本語（高度な能力）
      - 英語（ビジネスレベル）

  - title: Personal Project # Title for the section
    title_ja: 個人プロジェクト # 日本語タイトル
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      I run a small studio called **LuluLab**, which is inspired by my pet Lulu (a Peach-faced Lovebird).
      The studio primarily focuses on integrating the latest technologies in big data and AI to create interesting solutions.
        - Currently, there is a sub-project called [LuluEats](https://fast-order-xi.vercel.app/), which, as part of social contribution efforts, provides free digitalization assistance to startup restaurants. In the future, we will continuously integrate AI and IoT technologies into the daily operations of these restaurants.
    content_ja: | # 日本語コンテンツ
      私は**LuluLab**という小さなスタジオを運営しています。このスタジオの名前は、私のペットであるルル（ボタンインコ）にちなんで名付けられました。
      スタジオでは主に、ビッグデータとAIの最新技術を融合させ、面白いソリューションを開発することに注力しています。
        - 現在、「[LuluEats](https://fast-order-xi.vercel.app/)」というサブプロジェクトがあり、社会貢献の一環として、スタートアップのレストラン向けに無料のデジタル化支援を提供しています。将来的には、AIとIoT技術をレストランの日常業務に継続的に統合していく予定です。

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   sass_dir: _sass
#   style: compressed

# plugins:
  # - jekyll-seo-tag
