# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: GUANGYU QU
title: Analytics Engineer
email: quguangyu0321@gmail.com
website: https://medium.com/@quguangyu0321

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: quguangyu
linkedin_username: guangyu-qu-a51b661a6
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: redbook
  icon: fas fa-globe
  # icon: https://fontawesome.com/icons/book?f=classic&s=solid
  url: https://www.xiaohongshu.com/user/profile/5b1c88d96b58b70d9fb75e3e?xsec_token=YBhNsDHtxfT0xAyVm9ApdDk5dV7rMGmPMrLlLsLrB3wpI%3D&xsec_source=app_share&xhsshare=CopyLink&appuid=5b1c88d96b58b70d9fb75e3e&apptime=1741935998&share_id=0f9df8401db04df0ae65121a9324677d&share_channel=copy_link
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
    With 8 years of experience in Analytics Engineering at NTT GROUP, I have led to significant, continuous improvements in data systems.
    My expertise spans Fraud Analysis, Marketing, HR-tech, and IOT among other areas.
    
    I am proficient in <mark>Databases</mark>, <mark>CI/CD</mark>, <mark>Data Pipelines</mark>, <mark>Business Intelligence (BI)</mark>, <mark>Git</mark>, and <mark>Python</mark>, demonstrating a wide range of skills for different types of data problems.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: NTT Docomo Business
        link: https://www.ubigi.com/connected-cars/
        # link_text: boringcompany.com
        sub_title: Presales Engineer, Tokyo
        caption: December 2024 - Present
        description: | # this will include new lines to allow paragraphs
            - Led proposals and delivery support for both domestic and international connected car projects by understanding unique IT system requirements and collaborating with internal teams and global partners.
            - Acted as a solution architect, ensuring successful IT system delivery for connected car projects.
            - Spearheaded the planning, development, and cross-deployment of common features and value-added functions to drive contract wins, improve engagement, and reduce overall costs.
            - Independently designed and managed system architectures integrating mobile and IT technologies with multi-vendor platforms.

      - layout: left
        border: weak
        title: Transatel
        link: https://cellulardata.ubigi.com
        # link_text: boringcompany.com
        sub_title: Analystics Engineer, Paris
        caption: December 2023 - November 2024
        description: | # this will include new lines to allow paragraphs
              I play a dual role, contributing to both the Marketing and Business Intelligence (BI) teams.
              - Led in-depth marketing analysis for Ubigi's eSIM service(travel data from around the world), leveraging advanced data analytics to drive strategic decisions and enhance service offerings.
              - Collaborated closely with the Business Intelligence (BI) team to facilitate a seamless BI Platform Migration of the BI platform from on-premises to Snowflake, significantly improving data processing efficiency and scalability.

      - layout: left
        border: weak
        title: Docomo Pacific
        link: https://www.docomopacific.com
        # link_text: boringcompany.com
        sub_title: Analystics Engineer, Guam
        caption: April 2023 - September 2023
        description: | # this will include new lines to allow paragraphs
              I spearheaded a six-month project where I served as the lead trainer for Guam’s BI team.
              I designed and delivered interactive, hands-on workshops to empower them in mastering Power BI, while also providing expert guidance on executing comprehensive customer satisfaction survey analyses.

      - layout: left
        border: weak
        title: NTT Communications
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Analystics Engineer, Tokyo
        caption: April 2020 - November 2023
        description: | # this will include new lines to allow paragraphs
                 Work as an analysis consultant to help staff improve their analytical skills. Identifying problems in business processes and redesigning them in a modern digital way.
                 I also serve as a link between the data engineer and data analyst teams within the big data group. Create services and teach the analysis team how to use the system.
                 - I have experience in driving business transformation for the internal audit team by helping them efficiently analyze internal risk and perform effective audits.(Fraud Analysis)
                 - I supported the HR department by analyzing investigations of employee engagement. Through this role, I helped HR identify areas of concern and implemented solutions to improve employee satisfaction and retention.(HR Analysis)
                 - I led to discuss and build data modeling guildline in bigdata team. Standardlize the process from source layer to dwh layer and datamart layer(Data Modeling).
                 - I have experience in proof of concept and implementation of Data Virtualization solutions ( Denodo) and data catalog solutions to help users accelerate their analysis.

      - layout: left
        border: weak
        title: NTT Communications, Tokyo
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DBA+PM
        caption: April 2017 - March 2020
        description: | # this will include new lines to allow paragraphs
                Project Manager responsible for the maintenance of the on-premise Oracle EXADATA Database Machine platform. Reviewing daily tasks such as capacity planning, performance monitoring, security, backups, troubleshooting, and data recovery. 
                - Designing and implementing a disaster backup site in a different region to ensure business continuity.
                - Designing and implementing an ETL platform using OSS Talend Data Studio for the DWH team, resulting in faster data integration processes.

      - layout: left
        title: NTT Communications, Tokyo
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: April 2016 - March 2017
        description: | # this will include new lines to allow paragraphs
                  I have experience in developing a Master IT Facility Management System that collects and manages data from servers, network devices, and Excel files, providing reliable information via a web GUI for operators. 
                  - Constructing Linux/Windows servers and virtualized environments using Openstack, Docker, and Ansible in an on-premise setting.
                  - Designing and implementing a Storage Area Network (SAN) composed of servers, FC-switches, and VNX Storage.
                  - Installing and configuring a Zabbix-based monitoring system to monitor servers, storage, FC-switches, and developed applications running on servers.
                  - Writing automated web application tests using Selenium and Python.

  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - 2014-2016, Master(Cognitive and Behavioral Sciences), Kyoto University, Kyoto
      - 2009-2013, Bachelor(Information Sciences), Tianjin University, Tianjin

  - title: Languages # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - Mandarin(Native)
      - Japanese(High Proficiency)
      - English(Business)

  - title: Tech Stack # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - Database (Duckdb, Snowflake, Hadoop, Hive, Trino, Clickhouse, Kafka, Oracle, Mysql,etc)
      - BI Tools (Tableau, PowerBI, Superset, Streamlit)
      - Metadata Management(Datahub, OpenMetadata)
      - Data Virturalization (denodo, tibco)
      - ETL/ELT(DBT, Airflow, Talend, Airbyte)
      - Data Quality(Dbt test, Great expectations, Pytest)
      - Infra(K8S, Helm, ArgoCD,Ansible, Selenium, Sphinx,etc)
      - Log Management(Elasticsearch, Kibana, Logstash, Beatsfamily)
      - Microsoft Solution(GraphAPI, AzureAD, AzureSQL, WindowsServer etc)

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   sass_dir: _sass
#   style: compressed

# plugins:
#  - jekyll-seo-tag
